# Generated by Django 4.2.1 on 2023-09-08 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cource',
            fields=[
                ('course_id', models.AutoField(db_column='course_id', primary_key=True, serialize=False)),
                ('cource_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cource_master',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.AutoField(db_column='pid', default='1', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password1', models.CharField(default='', max_length=100)),
                ('password2', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('prog_id', models.AutoField(db_column='prog_id', primary_key=True, serialize=False)),
                ('program_code', models.IntegerField()),
                ('prog_name', models.CharField(max_length=100)),
                ('prog_duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'program_master',
            },
        ),
        migrations.CreateModel(
            name='subjectdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_code', models.IntegerField()),
                ('s_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('semester_id', models.AutoField(db_column='semester_id', primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.programmes', verbose_name='semester')),
            ],
            options={
                'db_table': 'semester_master',
            },
        ),
        migrations.CreateModel(
            name='Request_provisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField()),
                ('sem_pro', models.IntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.cource', verbose_name='cource')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Request_final_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField()),
                ('sem_pro1', models.IntegerField(default=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.cource', verbose_name='cource')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Request_bonafide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField()),
                ('reason', models.CharField(default='yash', max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.cource', verbose_name='cource')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.person')),
            ],
        ),
    ]
