# Generated by Django 4.2.1 on 2023-09-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_provisional',
            name='name',
        ),
    ]
