# Generated by Django 4.2.1 on 2023-09-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request_bonafide',
            old_name='cource_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='request_final_result',
            old_name='cource_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='request_provisional',
            old_name='cource_name',
            new_name='c_name',
        ),
        migrations.RemoveField(
            model_name='request_provisional',
            name='c_id1',
        ),
    ]
