# Generated by Django 4.2.1 on 2023-09-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0002_remove_request_provisional_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_provisional',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='request_provisional',
            name='div',
        ),
        migrations.RemoveField(
            model_name='request_provisional',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='request_provisional',
            name='sem',
        ),
    ]
