# Generated by Django 4.2.1 on 2023-08-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('prog_id', models.AutoField(db_column='prog_id', primary_key=True, serialize=False)),
                ('program_code', models.IntegerField()),
                ('prog_name', models.CharField(max_length=100)),
                ('prog_duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'program_master',
            },
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                ('semester_id', models.AutoField(db_column='semester_id', primary_key=True, serialize=False)),
                ('semester', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('prog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_app.programmes', verbose_name='semester')),
            ],
            options={
                'db_table': 'semester_master',
            },
        ),
    ]
