# Generated by Django 4.2.1 on 2023-09-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0002_rename_cource_name_request_bonafide_c_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cource',
            name='prog_id',
        ),
    ]
