# Generated by Django 4.2.1 on 2023-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0004_cource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_provisinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('div', models.IntegerField()),
                ('enrollment', models.IntegerField()),
                ('sem_pro', models.IntegerField()),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
    ]
