# Generated by Django 4.2.1 on 2023-08-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0005_request_provisinal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request_provisinal',
            new_name='Request_provisional',
        ),
    ]
