# Generated by Django 4.2.1 on 2023-09-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0006_request_provisional_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pid',
            field=models.AutoField(db_column='pid', default=1, primary_key=True, serialize=False),
        ),
    ]
