# Generated by Django 4.2.1 on 2023-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0006_rename_request_provisinal_request_provisional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_provisional',
            name='div',
            field=models.CharField(max_length=100),
        ),
    ]
