# Generated by Django 4.2.1 on 2023-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0007_alter_person_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pid',
            field=models.AutoField(db_column='pid', primary_key=True, serialize=False, unique=True),
        ),
    ]
