# Generated by Django 4.2.1 on 2023-09-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0008_alter_person_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_provisional',
            name='pid',
        ),
    ]
