# Generated by Django 4.2.1 on 2023-08-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0010_request_final_result_sem_pro1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_bonafide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField()),
                ('reason', models.CharField(default='xyz', max_length=500)),
            ],
        ),
    ]
