# Generated by Django 4.2.1 on 2023-09-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0010_request_provisional_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_provisional',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='person',
            name='enrollment',
            field=models.IntegerField(default=1),
        ),
    ]
