# Generated by Django 4.2.1 on 2023-09-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0011_remove_request_provisional_enrollment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='enrollment',
            field=models.IntegerField(default=''),
        ),
    ]
